---
# Sudo is required for some docker commands
sudo: required

services:
  - docker

# Run tests for each supported OS
#
# distro: Distro name corresponding to geerlingguy's docker images
# init: The init system corresponding to the distro
# run_opts: Additional arguments to pass when creating the docker container
env:
  - distro: ubuntu1604
    init: /lib/systemd/systemd
    run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"

# Pull latest version of docker image
before_install:
  - 'docker pull geerlingguy/docker-${distro}-ansible:latest'

# Start docker container and run tests
script:
  # Create random file to store container ID
  - container_id=$(mktemp)

  # Run container with role mounted inside
  - >
    docker run --detach --volume="${PWD}":/etc/ansible/roles/role_under_test:ro
    ${run_opts} geerlingguy/docker-${distro}-ansible:latest
    "${init}" > "${container_id}"

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
