---
- name: Create deployment user '{{ deploy_user }}'
  user:
    name: "{{ deploy_user }}"
    shell: "{{ deploy_user_shell }}"
    state: present

- name: Add authorized keys for {{ deploy_user }}
  authorized_key:
    user: "{{ deploy_user }}"
    key: "{{ lookup('file', item) }}"
  with_items:
    - "{{ deploy_user_public_keys }}"

- name: Add {{ deploy_user }} to sudoers
  lineinfile:
    dest: "/etc/sudoers"
    regexp: "{{ deploy_user }} ALL"
    line: "{{ deploy_user }} ALL=(ALL) NOPASSWD: ALL"
    state: present

- name: Create sudoers.d directory
  file:
    path: /etc/sudoers.d
    owner: root
    group: root
    mode: 0755
    state: directory

- name: Include sudoers.d directory in sudoers file
  lineinfile:
    dest: /etc/sudoers
    line: "#includedir /etc/sudoers.d"
    state: present
    validate: "/usr/sbin/visudo -cf %s"

- name: create sudoer file for admin
  template:
    src: sudoers.d.j2
    dest: "/etc/sudoers.d/{{ deploy_user }}"
    mode: 0440
    owner: root
    group: root
    validate: "/usr/sbin/visudo -cf %s"
