---
- name: Create deployment user '{{ deploy_user }}'
  user:
    name: "{{ deploy_user }}"
    shell: "{{ deploy_user_shell }}"
    state: present

- name: Add {{ deploy_user }} to sudoers
  lineinfile:
    dest: "/etc/sudoers"
    regexp: "{{ deploy_user }} ALL"
    line: "{{ deploy_user }} ALL=(ALL) NOPASSWD: ALL"
    state: present
